services:
  db:
    image: postgres:alpine
    ports:
      - 5732:5732
    volumes:
      - postgres_data_tanstarter:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tanstarter

volumes:
  postgres_data_tanstarter:
